import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.join(__dirname, '..')
const photosRoot = path.join(root, 'public', 'photos')
const outFile = path.join(root, 'src', 'data', 'gallery.generated.ts')

const IMAGE_RE = /\.(jpe?g|png|webp)$/i
/** Excludes cover.jpg, cover.JPG, "cover - Copy.jpg", etc. */
const COVER_RE = /^cover/i

function listGalleryFiles(slugDir) {
  if (!fs.existsSync(slugDir)) return []
  try {
    return fs
      .readdirSync(slugDir)
      .filter(
        (f) =>
          IMAGE_RE.test(f) && !COVER_RE.test(f) && !f.startsWith('.'),
      )
      .sort((a, b) =>
        a.localeCompare(b, undefined, { numeric: true, sensitivity: 'base' }),
      )
  } catch (err) {
    if (err && (err.code === 'EBUSY' || err.code === 'EPERM')) {
      console.warn(`[gallery] skipped ${slugDir} (file locked — try again)`)
      return []
    }
    throw err
  }
}

export function syncGallery() {
  /** @type {Record<string, Array<{ id: string, src: string, title: string }>>} */
  const galleryBySlug = {}

  if (fs.existsSync(photosRoot)) {
    let entries
    try {
      entries = fs.readdirSync(photosRoot, { withFileTypes: true })
    } catch (err) {
      if (err && (err.code === 'EBUSY' || err.code === 'EPERM')) {
        console.warn('[gallery] sync skipped (photos folder locked)')
        return
      }
      throw err
    }
    for (const entry of entries) {
      if (!entry.isDirectory()) continue
      const slug = entry.name
      const dir = path.join(photosRoot, slug)
      galleryBySlug[slug] = listGalleryFiles(dir).map((filename) => {
        const base = filename.replace(/\.[^.]+$/i, '')
        return {
          id: `${slug}-${base}`,
          src: `/photos/${slug}/${filename}`,
          title: '',
        }
      })
    }
  }

  const lines = [
    '// Auto-generated by scripts/sync-gallery.mjs — do not edit manually.',
    '// Re-run on dev/build when you add or remove files in public/photos/<slug>/',
    "import type { Photo } from '../types'",
    '',
    'export const galleryBySlug: Record<string, Photo[]> = ' +
      JSON.stringify(galleryBySlug, null, 2),
    '',
  ]

  fs.mkdirSync(path.dirname(outFile), { recursive: true })
  fs.writeFileSync(outFile, lines.join('\n'))
  console.log(`[gallery] synced ${Object.values(galleryBySlug).flat().length} photos`)
}

const isMain = process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])
if (isMain) syncGallery()
