// Auto-generated by scripts/sync-gallery.mjs — do not edit manually.
// Re-run on dev/build when you add or remove files in public/photos/<slug>/
import type { Photo } from '../types'

export const galleryBySlug: Record<string, Photo[]> = {
  "bts": [
    {
      "id": "bts-01",
      "src": "/photos/bts/01.jpg",
      "title": ""
    },
    {
      "id": "bts-02",
      "src": "/photos/bts/02.jpg",
      "title": ""
    },
    {
      "id": "bts-03",
      "src": "/photos/bts/03.jpg",
      "title": ""
    },
    {
      "id": "bts-04",
      "src": "/photos/bts/04.jpg",
      "title": ""
    },
    {
      "id": "bts-05",
      "src": "/photos/bts/05.jpg",
      "title": ""
    },
    {
      "id": "bts-06",
      "src": "/photos/bts/06.jpg",
      "title": ""
    },
    {
      "id": "bts-07",
      "src": "/photos/bts/07.jpg",
      "title": ""
    },
    {
      "id": "bts-08",
      "src": "/photos/bts/08.jpg",
      "title": ""
    },
    {
      "id": "bts-09",
      "src": "/photos/bts/09.jpg",
      "title": ""
    },
    {
      "id": "bts-10",
      "src": "/photos/bts/10.jpg",
      "title": ""
    },
    {
      "id": "bts-11",
      "src": "/photos/bts/11.jpg",
      "title": ""
    },
    {
      "id": "bts-12",
      "src": "/photos/bts/12.jpg",
      "title": ""
    },
    {
      "id": "bts-13",
      "src": "/photos/bts/13.JPG",
      "title": ""
    },
    {
      "id": "bts-14",
      "src": "/photos/bts/14.JPG",
      "title": ""
    },
    {
      "id": "bts-15",
      "src": "/photos/bts/15.JPG",
      "title": ""
    },
    {
      "id": "bts-16",
      "src": "/photos/bts/16.jpg",
      "title": ""
    },
    {
      "id": "bts-17",
      "src": "/photos/bts/17.jpg",
      "title": ""
    },
    {
      "id": "bts-18",
      "src": "/photos/bts/18.jpg",
      "title": ""
    }
  ],
  "celebrations": [
    {
      "id": "celebrations-01",
      "src": "/photos/celebrations/01.JPG",
      "title": ""
    },
    {
      "id": "celebrations-02",
      "src": "/photos/celebrations/02.JPG",
      "title": ""
    },
    {
      "id": "celebrations-03",
      "src": "/photos/celebrations/03.JPG",
      "title": ""
    },
    {
      "id": "celebrations-04",
      "src": "/photos/celebrations/04.JPG",
      "title": ""
    },
    {
      "id": "celebrations-05",
      "src": "/photos/celebrations/05.JPG",
      "title": ""
    },
    {
      "id": "celebrations-06",
      "src": "/photos/celebrations/06.JPG",
      "title": ""
    },
    {
      "id": "celebrations-07",
      "src": "/photos/celebrations/07.JPG",
      "title": ""
    },
    {
      "id": "celebrations-08",
      "src": "/photos/celebrations/08.JPG",
      "title": ""
    },
    {
      "id": "celebrations-09",
      "src": "/photos/celebrations/09.JPG",
      "title": ""
    },
    {
      "id": "celebrations-10",
      "src": "/photos/celebrations/10.jpg",
      "title": ""
    },
    {
      "id": "celebrations-11",
      "src": "/photos/celebrations/11.jpg",
      "title": ""
    },
    {
      "id": "celebrations-12",
      "src": "/photos/celebrations/12.jpg",
      "title": ""
    },
    {
      "id": "celebrations-13",
      "src": "/photos/celebrations/13.jpg",
      "title": ""
    },
    {
      "id": "celebrations-14",
      "src": "/photos/celebrations/14.jpg",
      "title": ""
    },
    {
      "id": "celebrations-15",
      "src": "/photos/celebrations/15.jpg",
      "title": ""
    },
    {
      "id": "celebrations-16",
      "src": "/photos/celebrations/16.jpg",
      "title": ""
    },
    {
      "id": "celebrations-17",
      "src": "/photos/celebrations/17.jpg",
      "title": ""
    },
    {
      "id": "celebrations-18",
      "src": "/photos/celebrations/18.jpg",
      "title": ""
    }
  ],
  "dance": [
    {
      "id": "dance-01",
      "src": "/photos/dance/01.JPG",
      "title": ""
    },
    {
      "id": "dance-02",
      "src": "/photos/dance/02.JPG",
      "title": ""
    },
    {
      "id": "dance-03",
      "src": "/photos/dance/03.JPG",
      "title": ""
    },
    {
      "id": "dance-04",
      "src": "/photos/dance/04.JPG",
      "title": ""
    },
    {
      "id": "dance-05",
      "src": "/photos/dance/05.JPG",
      "title": ""
    },
    {
      "id": "dance-06",
      "src": "/photos/dance/06.JPG",
      "title": ""
    },
    {
      "id": "dance-07",
      "src": "/photos/dance/07.JPG",
      "title": ""
    },
    {
      "id": "dance-08",
      "src": "/photos/dance/08.JPG",
      "title": ""
    },
    {
      "id": "dance-09",
      "src": "/photos/dance/09.JPG",
      "title": ""
    },
    {
      "id": "dance-10",
      "src": "/photos/dance/10.JPG",
      "title": ""
    },
    {
      "id": "dance-11",
      "src": "/photos/dance/11.JPG",
      "title": ""
    },
    {
      "id": "dance-12",
      "src": "/photos/dance/12.JPG",
      "title": ""
    },
    {
      "id": "dance-13",
      "src": "/photos/dance/13.JPG",
      "title": ""
    },
    {
      "id": "dance-14",
      "src": "/photos/dance/14.JPG",
      "title": ""
    },
    {
      "id": "dance-15",
      "src": "/photos/dance/15.JPG",
      "title": ""
    }
  ],
  "events": [
    {
      "id": "events-01",
      "src": "/photos/events/01.JPG",
      "title": ""
    },
    {
      "id": "events-02",
      "src": "/photos/events/02.JPG",
      "title": ""
    },
    {
      "id": "events-03",
      "src": "/photos/events/03.jpg",
      "title": ""
    },
    {
      "id": "events-04",
      "src": "/photos/events/04.jpg",
      "title": ""
    },
    {
      "id": "events-05",
      "src": "/photos/events/05.jpg",
      "title": ""
    },
    {
      "id": "events-06",
      "src": "/photos/events/06.jpg",
      "title": ""
    },
    {
      "id": "events-07",
      "src": "/photos/events/07.jpg",
      "title": ""
    },
    {
      "id": "events-08",
      "src": "/photos/events/08.jpg",
      "title": ""
    },
    {
      "id": "events-09",
      "src": "/photos/events/09.jpg",
      "title": ""
    },
    {
      "id": "events-10",
      "src": "/photos/events/10.jpg",
      "title": ""
    },
    {
      "id": "events-11",
      "src": "/photos/events/11.jpg",
      "title": ""
    },
    {
      "id": "events-12",
      "src": "/photos/events/12.jpg",
      "title": ""
    },
    {
      "id": "events-13",
      "src": "/photos/events/13.JPG",
      "title": ""
    },
    {
      "id": "events-14",
      "src": "/photos/events/14.JPG",
      "title": ""
    },
    {
      "id": "events-15",
      "src": "/photos/events/15.JPG",
      "title": ""
    },
    {
      "id": "events-16",
      "src": "/photos/events/16.jpg",
      "title": ""
    },
    {
      "id": "events-17",
      "src": "/photos/events/17.jpg",
      "title": ""
    },
    {
      "id": "events-18",
      "src": "/photos/events/18.jpg",
      "title": ""
    },
    {
      "id": "events-19",
      "src": "/photos/events/19.jpg",
      "title": ""
    },
    {
      "id": "events-20",
      "src": "/photos/events/20.jpg",
      "title": ""
    },
    {
      "id": "events-21",
      "src": "/photos/events/21.jpg",
      "title": ""
    }
  ],
  "graduations": [
    {
      "id": "graduations-01",
      "src": "/photos/graduations/01.JPG",
      "title": ""
    },
    {
      "id": "graduations-02",
      "src": "/photos/graduations/02.JPG",
      "title": ""
    },
    {
      "id": "graduations-03",
      "src": "/photos/graduations/03.JPG",
      "title": ""
    },
    {
      "id": "graduations-04",
      "src": "/photos/graduations/04.JPG",
      "title": ""
    },
    {
      "id": "graduations-05",
      "src": "/photos/graduations/05.JPG",
      "title": ""
    },
    {
      "id": "graduations-06",
      "src": "/photos/graduations/06.JPG",
      "title": ""
    },
    {
      "id": "graduations-07",
      "src": "/photos/graduations/07.JPG",
      "title": ""
    },
    {
      "id": "graduations-08",
      "src": "/photos/graduations/08.JPG",
      "title": ""
    },
    {
      "id": "graduations-09",
      "src": "/photos/graduations/09.JPG",
      "title": ""
    },
    {
      "id": "graduations-10",
      "src": "/photos/graduations/10.JPG",
      "title": ""
    },
    {
      "id": "graduations-11",
      "src": "/photos/graduations/11.JPG",
      "title": ""
    },
    {
      "id": "graduations-12",
      "src": "/photos/graduations/12.JPG",
      "title": ""
    },
    {
      "id": "graduations-13",
      "src": "/photos/graduations/13.jpg",
      "title": ""
    },
    {
      "id": "graduations-14",
      "src": "/photos/graduations/14.jpg",
      "title": ""
    },
    {
      "id": "graduations-15",
      "src": "/photos/graduations/15.jpg",
      "title": ""
    },
    {
      "id": "graduations-16",
      "src": "/photos/graduations/16.JPG",
      "title": ""
    },
    {
      "id": "graduations-17",
      "src": "/photos/graduations/17.JPG",
      "title": ""
    },
    {
      "id": "graduations-18",
      "src": "/photos/graduations/18.JPG",
      "title": ""
    }
  ],
  "kids": [
    {
      "id": "kids-01",
      "src": "/photos/kids/01.JPG",
      "title": ""
    },
    {
      "id": "kids-02",
      "src": "/photos/kids/02.JPG",
      "title": ""
    },
    {
      "id": "kids-03",
      "src": "/photos/kids/03.JPG",
      "title": ""
    },
    {
      "id": "kids-04",
      "src": "/photos/kids/04.jpg",
      "title": ""
    },
    {
      "id": "kids-05",
      "src": "/photos/kids/05.jpg",
      "title": ""
    },
    {
      "id": "kids-06",
      "src": "/photos/kids/06.jpg",
      "title": ""
    },
    {
      "id": "kids-07",
      "src": "/photos/kids/07.jpg",
      "title": ""
    },
    {
      "id": "kids-08",
      "src": "/photos/kids/08.jpg",
      "title": ""
    },
    {
      "id": "kids-09",
      "src": "/photos/kids/09.jpg",
      "title": ""
    },
    {
      "id": "kids-10",
      "src": "/photos/kids/10.jpg",
      "title": ""
    },
    {
      "id": "kids-11",
      "src": "/photos/kids/11.jpg",
      "title": ""
    },
    {
      "id": "kids-12",
      "src": "/photos/kids/12.jpg",
      "title": ""
    },
    {
      "id": "kids-13",
      "src": "/photos/kids/13.jpg",
      "title": ""
    },
    {
      "id": "kids-14",
      "src": "/photos/kids/14.jpg",
      "title": ""
    },
    {
      "id": "kids-15",
      "src": "/photos/kids/15.jpg",
      "title": ""
    },
    {
      "id": "kids-16",
      "src": "/photos/kids/16.jpg",
      "title": ""
    },
    {
      "id": "kids-17",
      "src": "/photos/kids/17.jpg",
      "title": ""
    },
    {
      "id": "kids-18",
      "src": "/photos/kids/18.jpg",
      "title": ""
    }
  ],
  "portraits": [
    {
      "id": "portraits-01",
      "src": "/photos/portraits/01.jpg",
      "title": ""
    },
    {
      "id": "portraits-02",
      "src": "/photos/portraits/02.jpg",
      "title": ""
    },
    {
      "id": "portraits-03",
      "src": "/photos/portraits/03.jpg",
      "title": ""
    },
    {
      "id": "portraits-04",
      "src": "/photos/portraits/04.JPG",
      "title": ""
    },
    {
      "id": "portraits-05",
      "src": "/photos/portraits/05.JPG",
      "title": ""
    },
    {
      "id": "portraits-06",
      "src": "/photos/portraits/06.JPG",
      "title": ""
    },
    {
      "id": "portraits-07",
      "src": "/photos/portraits/07.jpg",
      "title": ""
    },
    {
      "id": "portraits-08",
      "src": "/photos/portraits/08.jpg",
      "title": ""
    },
    {
      "id": "portraits-09",
      "src": "/photos/portraits/09.jpg",
      "title": ""
    },
    {
      "id": "portraits-10",
      "src": "/photos/portraits/10.JPG",
      "title": ""
    },
    {
      "id": "portraits-11",
      "src": "/photos/portraits/11.JPG",
      "title": ""
    },
    {
      "id": "portraits-12",
      "src": "/photos/portraits/12.JPG",
      "title": ""
    },
    {
      "id": "portraits-13",
      "src": "/photos/portraits/13.jpg",
      "title": ""
    },
    {
      "id": "portraits-14",
      "src": "/photos/portraits/14.jpg",
      "title": ""
    },
    {
      "id": "portraits-15",
      "src": "/photos/portraits/15.jpg",
      "title": ""
    }
  ],
  "real-estate": [
    {
      "id": "real-estate-01",
      "src": "/photos/real-estate/01.JPG",
      "title": ""
    },
    {
      "id": "real-estate-02",
      "src": "/photos/real-estate/02.JPG",
      "title": ""
    },
    {
      "id": "real-estate-03",
      "src": "/photos/real-estate/03.JPG",
      "title": ""
    },
    {
      "id": "real-estate-04",
      "src": "/photos/real-estate/04.JPG",
      "title": ""
    },
    {
      "id": "real-estate-05",
      "src": "/photos/real-estate/05.JPG",
      "title": ""
    },
    {
      "id": "real-estate-06",
      "src": "/photos/real-estate/06.JPG",
      "title": ""
    }
  ],
  "sports": [
    {
      "id": "sports-01",
      "src": "/photos/sports/01.jpg",
      "title": ""
    },
    {
      "id": "sports-02",
      "src": "/photos/sports/02.jpg",
      "title": ""
    },
    {
      "id": "sports-03",
      "src": "/photos/sports/03.jpg",
      "title": ""
    },
    {
      "id": "sports-04",
      "src": "/photos/sports/04.jpg",
      "title": ""
    },
    {
      "id": "sports-05",
      "src": "/photos/sports/05.jpg",
      "title": ""
    },
    {
      "id": "sports-06",
      "src": "/photos/sports/06.jpg",
      "title": ""
    },
    {
      "id": "sports-07",
      "src": "/photos/sports/07.jpg",
      "title": ""
    },
    {
      "id": "sports-08",
      "src": "/photos/sports/08.jpg",
      "title": ""
    },
    {
      "id": "sports-09",
      "src": "/photos/sports/09.jpg",
      "title": ""
    },
    {
      "id": "sports-10",
      "src": "/photos/sports/10.jpg",
      "title": ""
    },
    {
      "id": "sports-11",
      "src": "/photos/sports/11.jpg",
      "title": ""
    },
    {
      "id": "sports-12",
      "src": "/photos/sports/12.jpg",
      "title": ""
    },
    {
      "id": "sports-13",
      "src": "/photos/sports/13.jpg",
      "title": ""
    },
    {
      "id": "sports-14",
      "src": "/photos/sports/14.jpg",
      "title": ""
    },
    {
      "id": "sports-15",
      "src": "/photos/sports/15.jpg",
      "title": ""
    },
    {
      "id": "sports-16",
      "src": "/photos/sports/16.PNG",
      "title": ""
    },
    {
      "id": "sports-17",
      "src": "/photos/sports/17.PNG",
      "title": ""
    },
    {
      "id": "sports-18",
      "src": "/photos/sports/18.PNG",
      "title": ""
    }
  ]
}
